name: perfume_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  animated_cross_fade_plus: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Hellix
      fonts:
        - asset: assets/fonts/Hellix-Black.ttf
        - asset: assets/fonts/Hellix-Bold.ttf
        - asset: assets/fonts/Hellix-ExtraBold.ttf
        - asset: assets/fonts/Hellix-Light.ttf
        - asset: assets/fonts/Hellix-Medium.ttf
        - asset: assets/fonts/Hellix-Regular.ttf
        - asset: assets/fonts/Hellix-SemiBold.ttf
        - asset: assets/fonts/Hellix-Thin.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
